[project]
name = "hexlet-code"
version = "0.1.0"
description = "Compares two configuration files and shows a difference."
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[project.scripts]
gendiff = "hexlet_code.scripts.gendiff:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
<<<<<<< HEAD
packages = ["src/hexlet_code"]
=======
packages = ["hexlet_code"]
>>>>>>> 831294c (Add --format option and fix package installation)
